on:
  release:
    types: [published]

name: Deploy Rocket Plugin on Dev
jobs:
  deploy:
    name: Deploy Rocket Plugin on Dev
    runs-on: ubuntu-latest
    steps:
      - name: checkout
        uses: actions/checkout@v2
      - name: test
        run: echo ${GITHUB_REF#refs/v*/}
