on:
  release:
    types:
      - published
      - edited

name: Deploy Rocket Plugin on Dev
jobs:
  deploy:
    name: Deploy Rocket Plugin on Dev
    runs-on: ubuntu-latest
    steps:
      - name: checkout
        uses: actions/checkout@v2
      - name: test
        run: |
          # To keep format, we cut the first character of the tag ('v').
          export KK=$(echo ${ GITHUB_REF#refs/*/ } | cut -c 2-)
          echo $KK
